### PR TITLE
Added handling for cases where the remoteUrl is more complex

### PR DESCRIPTION
**Pull request by chris-grabcad**
for example we're using artifactory https://x.y.z/api/npm/npm-repo
because we're hosting jfrog's artifactory behind nginx

### CODE REVIEW

**Comment by chris-grabcad** [comment]
Not ready yet - sorry

**Comment by chris-grabcad** [comment]
Ok - ready now :-)

**Comment by chris-grabcad** [comment]
@CL0Sey, @mixu Could someone take a look at this please?

**Comment by CL0SeY** [comment]
Is this still needed? Sorry for the delay.

I can probably have a look at testing this potentially.

**Comment by chris-grabcad** [comment]
We have made a private branch and are using that via our own npm repo, and
it's necessary if you want to d/l from your own repo (with nested paths).

**Comment by chris-grabcad** [comment]
nvm - we're using yarn now :-)

**Pull request closed without merging**
