### PR TITLE
Fix port null when using ssl via nexus

### PR DESCRIPTION
**Pull request by zaghbizied**

### CODE REVIEW

**Comment by CL0SeY** [comment]
This looks good to me.

Has it been tested with regular use and with HTTPS? Also excuse my ignorance, what is nexus? :)

Cheers!

**Comment by zaghbizied** [comment]
Hello, Nexus is a private repository manager just like npm registry. We use it to publish private packages.
I have tested this only with nexus, i will do some other tests and get back to you.
Regards

**Comment by mixu** [comment]
awesome, thanks!

**Comment by mixu** [comment]
published on npm as `v1.14.0`

**Pull request merged**
